--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/theSpawn
build-by-default: true
branches:
- master
- Dev
- PM4
projects:
  theSpawn:
    icon: "icon.png"
    path: ""
    php: 8.0
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3